source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMMAppUpdater_Example', :exclusive => true do
  pod "MMMAppUpdater", :path => "../"
end

target 'MMMAppUpdater_Tests', :exclusive => true do
  pod "MMMAppUpdater", :path => "../"

  
end
